repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-2_T02_IRM-MARY-KELLER
repo_name: 2025-2_T02_IRM-MARY-KELLER

site_name: Grupo IRMA-MARY-KELLER - Turma 2 (2025.2)
site_description: Documentação do projeto do grupo IRMA-MARY-KELLER de Qualidade de Software (2024.2), Turma 2

nav:
  - Home: index.md
  - Fase 1: fase_1/fase_1.md
  - Fase 2 - Especificação da Avaliação:
    - Abordagem GQM: "fase_2/GQM.md"
    - Medição 1 - Compatibilidade: "fase_2/compatibilidade.md"
    - Medição 2 - Portabilidade: "fase_2/portabilidade.md"
    - Conclusão: "fase_2/conclusao.md"
  - Fase 3 - Projeto de Avaliação:
    - Planejamento da Avaliação: "fase_3/planejamento.md"
    - Testes de Compatibilidade: "fase_3/compatibilidade.md"
    - Testes de Portabilidade: "fase_3/portabilidade.md"
    - Cronograma de ações: "fase_3/cronograma.md"
    - Ferramentas e Ambiente: "fase_3/ferramentas.md"

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
    - scheme: high-contrast
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-cloudy-alert
        name: Switch to high contrast
  logo: assets/img/logo.png

markdown_extensions:
  - md_in_html
  - attr_list
